### ISSUE TITLE
Personal issue

### ISSUE THREAD

**Issue by Dadik11** [joseph-gerald/ai-js-id-renamer#1]
💀💐💐

**Comment by BennyTian** [comment]
show me your code

**Comment by joseph-gerald** [comment]
> show me your code 

what

**Comment by BennyTian** [comment]
Does this project have any code ?  thx !

**Comment by joseph-gerald** [comment]
> Does this project have any code ? thx !

Sorry not yet, if you wanna start the project off it would be appreciated.
